# Generated by Django 5.2.4 on 2025-07-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag_project_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
